<?php
// Admin page for recording and reviewing student discipline cases.
$page_title='Discipline Management'; $page_heading='Discipline Management';
require_once 'config/database.php'; require_once 'includes/auth.php'; require_role(['admin']);
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 try{
  $action=$_POST['action']??'create';
  if($action==='create'){
   $stmt=$pdo->prepare('INSERT INTO violations(student_id,violation_type,category,description,incident_date,location,reported_by,sanction,status) VALUES(?,?,?,?,?,?,?,?,?)');
   $stmt->execute([$_POST['student_id'],$_POST['violation_type'],trim($_POST['category']??'Other'),trim($_POST['description']??''),$_POST['incident_date'],trim($_POST['location']??''),trim($_POST['reported_by']??''),trim($_POST['sanction']??''),'pending']);
   $q=$pdo->prepare('SELECT id FROM violations WHERE student_id=? AND incident_date=? ORDER BY created_at DESC LIMIT 1');$q->execute([$_POST['student_id'],$_POST['incident_date']]);$id=$q->fetchColumn();log_action($pdo,'created','Discipline',$id,'Recorded a student discipline case.');$message='Discipline case recorded successfully.';
  }elseif($action==='update'){
   $status=$_POST['status']??'pending';$resolved= in_array($status,['resolved','dismissed'],true) ? date('Y-m-d H:i:s') : null;
   $stmt=$pdo->prepare('UPDATE violations SET violation_type=?,category=?,description=?,incident_date=?,location=?,reported_by=?,sanction=?,status=?,resolution_notes=?,resolved_date=? WHERE id=?');
   $stmt->execute([$_POST['violation_type'],trim($_POST['category']??''),trim($_POST['description']??''),$_POST['incident_date'],trim($_POST['location']??''),trim($_POST['reported_by']??''),trim($_POST['sanction']??''),$status,trim($_POST['resolution_notes']??''),$resolved,$_POST['id']]);log_action($pdo,'updated','Discipline',$_POST['id'],'Updated discipline case status/details.');$message='Discipline case updated successfully.';
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
$students=$pdo->query("SELECT id,student_number,first_name,last_name FROM students WHERE status='active' ORDER BY last_name")->fetchAll();
$rows=$pdo->query("SELECT v.*,s.student_number,CONCAT(s.first_name,' ',s.last_name) student_name FROM violations v JOIN students s ON s.id=v.student_id ORDER BY v.created_at DESC")->fetchAll();include 'includes/header.php';
?>
<?php if($message):?><div class="alert success"><?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert danger"><?=htmlspecialchars($error)?></div><?php endif;?>
<div class="page-actions"><p class="muted">Record cases and move them through Pending → Under Review → Resolved or Dismissed. Resolution details are retained for reporting.</p><button class="btn primary" onclick="openModal('violationModal')">+ Record Violation</button></div>
<section class="card"><div class="search"><input id="tableSearch" placeholder="Search discipline records..."></div><table id="dataTable"><thead><tr><th>Student</th><th>Type</th><th>Category</th><th>Description</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><?=htmlspecialchars($r['student_number'].' - '.$r['student_name'])?></td><td><span class="badge <?=$r['violation_type']==='major'?'red':'gold'?>"><?=htmlspecialchars($r['violation_type'])?></span></td><td><?=htmlspecialchars($r['category'])?></td><td><?=htmlspecialchars($r['description'])?></td><td><span class="badge <?=$r['status']==='resolved'?'green':($r['status']==='dismissed'?'red':'gold')?>"><?=htmlspecialchars(str_replace('_',' ',$r['status']))?></span></td><td><?=htmlspecialchars($r['incident_date'])?></td><td><button class="btn secondary" type="button" onclick='editViolation(<?=json_encode($r)?>)'>Manage Case</button></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7">No discipline records found.</td></tr><?php endif;?></tbody></table></section>
<div class="modal" id="violationModal"><div class="modal-box"><button class="close" onclick="closeModal('violationModal')">×</button><h2 id="violationTitle">Record Violation</h2><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrf_token(),ENT_QUOTES)?>"><input type="hidden" name="action" id="violationAction" value="create"><input type="hidden" name="id" id="violationId"><label>Student<select name="student_id" id="student_id" required><option value="">Select student</option><?php foreach($students as $s):?><option value="<?=$s['id']?>"><?=htmlspecialchars($s['student_number'].' - '.$s['last_name'].', '.$s['first_name'])?></option><?php endforeach;?></select></label><label>Type<select name="violation_type" id="violation_type"><option>minor</option><option>major</option></select></label><label>Category<input name="category" id="category" value="Other"></label><label>Incident Date<input type="date" name="incident_date" id="incident_date" value="<?=date('Y-m-d')?>" required></label><label class="wide">Description<textarea name="description" id="description" required></textarea></label><label>Location<input name="location" id="location"></label><label>Reported By<input name="reported_by" id="reported_by"></label><label class="wide">Sanction<input name="sanction" id="sanction"></label><label>Status<select name="status" id="caseStatus"><option>pending</option><option>under_review</option><option>resolved</option><option>dismissed</option></select></label><label class="wide">Resolution Notes<textarea name="resolution_notes" id="resolution_notes"></textarea></label><div class="form-end"><button class="btn primary">Save Case</button></div></form></div></div>
<script>function editViolation(v){document.getElementById('violationTitle').textContent='Manage Discipline Case';document.getElementById('violationAction').value='update';document.getElementById('violationId').value=v.id;['student_id','violation_type','category','incident_date','description','location','reported_by','sanction','resolution_notes'].forEach(k=>{const e=document.getElementById(k);if(e)e.value=v[k]??''});document.getElementById('caseStatus').value=v.status;openModal('violationModal')}</script>
<?php include 'includes/footer.php'; ?>
